import Head from "next/head";
import Sidebar from "@/components/Sidebar";
import { Inter } from "@next/font/google";
import Feed from "@/components/Feed";
import CommentModal from "@/components/CommentModal";
import Widgets from "@/components/Widgets";
import { FC } from "react";
import { Article, RandomUser } from "@/types/widgets";

const inter = Inter({ subsets: ["latin"] });

export default function Home({
  newsResults,
  randomUsersResults,
}: {
  newsResults: Article[];
  randomUsersResults: RandomUser[];
}) {
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen mx-auto">
        <Sidebar />
        <Feed />
        <Widgets
          newsResults={newsResults}
          randomUsersResults={randomUsersResults}
        />
        <CommentModal />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  let newsResults: Article[] = [];
  let randomUsersResults: RandomUser[] = [];

  try {
    let response = await fetch(
      "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
    );
    let data = await response.json();
    newsResults = data?.articles || [];
  } catch (error) {
    newsResults = [];
  }

  try {
    let response = await fetch(
      "https://randomuser.me/api/?results=30&inc=name,login,picture"
    );
    let data = await response.json();
    randomUsersResults = data?.results || [];
  } catch (error) {
    randomUsersResults = [];
  }

  return {
    props: {
      newsResults,
      randomUsersResults,
    },
  };
}
